### ISSUE TITLE
Unable to send whatsapp messages.

### ISSUE THREAD

**Issue by wasey-rao** [mhamidjamil/TTGO_TCall#112]

**Comment by wasey-rao** [comment]
Unable to whatsapp functionality via BLE and some time with BLE, i get -1 http error code, 

![Image](https://github.com/mhamidjamil/TTGO_TCall/assets/56353262/d8e0c72f-abf5-4eb1-96cb-bc35d4b12ba7)

 is the screen shot

**Comment by mhamidjamil** [comment]
I checked ![image](https://github.com/mhamidjamil/TTGO_TCall/assets/55445517/e1491f6d-1916-4eb9-87e6-c6af1436c44d)this issue; it is almost working fine if we just use serial terminal but failed when we use BLE.

**Comment by mhamidjamil** [comment]
I think BLE cause some kind of disturbance in WIFI connectivity, so the WIFI part doesn't work as expected, still gathering more information.
my conclusion is:
when we connect with BLE WIFI don't work as expected that's why the http request failed,
![Screenshot 2023-10-04 015616](https://github.com/mhamidjamil/TTGO_TCall/assets/55445517/b496a4d8-3e8c-4282-90ea-4af0b2e3cc63)

**Comment by mhamidjamil** [comment]
My conclusion is: enqueue Wi-Fi related jobs and execute when BLE device disconnect and also suggest that if BLE connected device is not sending any data for a specific duration then it should be disconnected.
